#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Oct 26, 2019 09:43:20 PM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 1256x700+334+153
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Blood Bank Management System - Login"
    vTcl:DefineAlias "$top" "login" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab43 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 20} -foreground $vTcl(actual_gui_fg) \
        -text {User ID} 
    vTcl:DefineAlias "$top.lab43" "Label1" vTcl:WidgetProc "login" 1
    label $top.lab44 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 20} -foreground $vTcl(actual_gui_fg) \
        -text Password 
    vTcl:DefineAlias "$top.lab44" "Label2" vTcl:WidgetProc "login" 1
    entry $top.ent45 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 20} -foreground $vTcl(actual_gui_fg) \
        -insertbackground black -selectforeground #ffffffffffff 
    vTcl:DefineAlias "$top.ent45" "Entry1" vTcl:WidgetProc "login" 1
    entry $top.ent46 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 20} -foreground $vTcl(actual_gui_fg) \
        -insertbackground #000000 -readonlybackground #f0f0f0f0f0f0 -show * 
    vTcl:DefineAlias "$top.ent46" "Entry2" vTcl:WidgetProc "login" 1
    button $top.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Login 
    vTcl:DefineAlias "$top.but47" "Button1" vTcl:WidgetProc "login" 1
    label $top.lab48 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Verdana} -size 28} -foreground $vTcl(actual_gui_fg) \
        -text {Administrator Login} 
    vTcl:DefineAlias "$top.lab48" "Label3" vTcl:WidgetProc "login" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 90 -y 220 -width 184 -relwidth 0 -height 60 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 100 -y 390 -width 174 -relwidth 0 -height 41 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent45 \
        -in $top -x 360 -y 210 -width 750 -relwidth 0 -height 60 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 360 -y 370 -width 750 -relwidth 0 -height 60 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 460 -y 510 -width 337 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 460 -y 90 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

