#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Oct 26, 2019 09:43:18 PM IST  platform: Windows NT

import sys
import hashlib
sys.path.append('C:\\page\\bbms\\controller')
import login_Check

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import login_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = login (root)
    login_support.init(root, top)
    root.mainloop()

w = None
def create_login(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = login (w)
    login_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_login():
    global w
    w.destroy()
    w = None

class login:
    def loginUser(self):
        user_id = self.Entry1.get()
        password = str(hashlib.sha256((self.Entry2.get()).encode()).hexdigest())
        chk = login_Check.loginCheck(user_id,password)
        print(chk[0], chk[1])


    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Segoe UI} -size 20 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font13 = "-family Verdana -size 28 -weight normal -slant roman"  \
            " -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 16 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("1256x700+334+153")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(0, 0)
        top.title("Blood Bank Management System - Login")
        top.configure(background="#d9d9d9")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.072, rely=0.314, height=60, width=184)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''User ID''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.08, rely=0.557, height=41, width=174)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Password''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.287, rely=0.3,height=60, relwidth=0.597)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font=font10)
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectforeground="#ffffffffffff")

        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.287, rely=0.529,height=60, relwidth=0.597)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font=font10)
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="#000000")
        self.Entry2.configure(readonlybackground="#f0f0f0f0f0f0")
        self.Entry2.configure(show="*")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.366, rely=0.729, height=44, width=337)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font9)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Login''')
        self.Button1.configure(command=self.loginUser)

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.366, rely=0.129, height=51, width=370)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font13)
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Administrator Login''')

if __name__ == '__main__':
    vp_start_gui()





